# Generated by Django 4.2.2 on 2024-05-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=100)),
                ('Nombre_Producto', models.CharField(max_length=150)),
                ('Marca', models.CharField(max_length=150)),
                ('Precio', models.IntegerField()),
            ],
        ),
    ]
